# plug.kak
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload
plug "andreyorst/smarttab.kak"
plug "kak-lsp/kak-lsp" do %{
    cargo install --locked --force --path .
}

# smash escape
hook global InsertChar j %{ try %{
      exec -draft hH <a-k>jj<ret> d
        exec <esc>
}}

# relative line numbers
add-highlighter global/ number-lines -relative

# 4 spaces per tab
set-option global indentwidth 4

# use case insensitive search
map global normal / '/(?i)'

