require("native.leader")
require("native.options")
require("native.keymaps")
require("native.diagnostics")
require("native.autocmds")
require("native.dev")
require("native.pack")
require("native.lsp")

require("plugins.telescope")
require("plugins.oil")
require("plugins.tree-sitter-manager")
require("plugins.todo-comments")
require("plugins.gitsigns")
require("plugins.conform")
require("plugins.nvim-eslint")
require("plugins.theme")
